---
server_env: production

# Git settings
setup_git_repo: yes
git_branch: master


# PostgreSQL
db_user: "{{ project_name }}"
db_name: "{{ project_name }}"
db_password: Altitude123!


# MySQL
mysql_db_user: "{{ db_user }}"
mysql_db_name: "{{ db_name }}"
mysql_db_password: "{{ db_password }}"
mysql_port: 3306

# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 5

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0


# Nginx settings
nginx_server_name: askmetisa.com
nginx_with_ssl: true
ssl_src_dir: ssl_self_signed
ssl_dest_dir: /etc/ssl
ssl_key_password: ''


# RabbitMQ settings
rabbitmq_server_name: "{{ inventory_hostname }}"

rabbitmq_admin_user: admin
rabbitmq_admin_password: password

rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password


# Celery settings
celery_num_workers: 2
flower_admin_password: password


# Application settings
django_settings_file: "{{ application_name }}.settings.production"
django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"
run_django_makemigrations: no
run_django_collectstatic: yes


ssl_crt: |
  -----BEGIN CERTIFICATE-----
  MIIFTDCCBDSgAwIBAgIRAIZso/M28OdgvfFXYxomdAYwDQYJKoZIhvcNAQELBQAw
  gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
  BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
  VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
  Q0EwHhcNMTYxMTMwMDAwMDAwWhcNMTcxMTMwMjM1OTU5WjBRMSEwHwYDVQQLExhE
  b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxFDASBgNVBAsTC1Bvc2l0aXZlU1NMMRYw
  FAYDVQQDEw1hc2ttZXRpc2EuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
  CgKCAQEA4K6O9PqrVqrpm96BUVk+6PXU4bKBG0YVOA/SyJzRR2apJGlpf+V8WNWU
  hDEd2g6K4Z2k5VTnVFjbzGH8IKNQD+tQ2ozDPfTGxdfj9ZML0L2G6+fRjx+L5qdA
  HF7i+kbc4ghnDyzM3laMQcn18dNzH3OWhBT1YmCxkvwiKBECXPHMHJrbGOg/+pG2
  ULM6RhJsvkVlyYSnG8O6cDfXv4XH18tpabxQOGRmzRh0IreTXUKoxnXOOBiaXj/g
  cGUyLU64tRj3CWxk6+N3GJbn6V8ncv2dLh1nJ5mFNqFXFxPLoHSuxxTMXm4g74yj
  yfTOEiC+Eq+mGlTIlIk1QI6Stcpi1wIDAQABo4IB3TCCAdkwHwYDVR0jBBgwFoAU
  kK9qOpRaC9iQ6hJWc99DtDoo2ucwHQYDVR0OBBYEFO9/pJBEa8lfUXk2uK7gmYnQ
  SeWWMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsG
  AQUFBwMBBggrBgEFBQcDAjBPBgNVHSAESDBGMDoGCysGAQQBsjEBAgIHMCswKQYI
  KwYBBQUHAgEWHWh0dHBzOi8vc2VjdXJlLmNvbW9kby5jb20vQ1BTMAgGBmeBDAEC
  ATBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vY3JsLmNvbW9kb2NhLmNvbS9DT01P
  RE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3JsMIGFBggrBgEF
  BQcBAQR5MHcwTwYIKwYBBQUHMAKGQ2h0dHA6Ly9jcnQuY29tb2RvY2EuY29tL0NP
  TU9ET1JTQURvbWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJDQS5jcnQwJAYIKwYB
  BQUHMAGGGGh0dHA6Ly9vY3NwLmNvbW9kb2NhLmNvbTArBgNVHREEJDAigg1hc2tt
  ZXRpc2EuY29tghF3d3cuYXNrbWV0aXNhLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEA
  KOndlhwK4elV9Js6lAOVyWhJqPJaxAqPToN/c7LjRP+NqAoET/9PPtB+XRfEWgef
  OqF4H8kyE5NTSGOyCVmBwIcklTc3hBoZN8RsD15VXzvVPQl59M4u0zd3E7Jf99qq
  bYPyhB02/ur4IDQ5ImXKAGVQQ5vAJHQRZA4u63ZzxFSruRjsb6Tb3W6JZ5rzH/Pc
  dh6n+C3ITDTdyL4qAT5YqtD6KVR5vMBBbVvnuZ3Wj3acsBsu5S6+Dzv0DhrQGV7f
  AHXY5ZwRZTt+pfeunfBq6FKCURueoGu5FBMdCopJVVekkHXxeHlHw/lu5ZSBYzEv
  XxZ4TGTS0lUbkmCLzr3cWA==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIGCDCCA/CgAwIBAgIQKy5u6tl1NmwUim7bo3yMBzANBgkqhkiG9w0BAQwFADCB
  hTELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
  A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKzApBgNV
  BAMTIkNPTU9ETyBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMjEy
  MDAwMDAwWhcNMjkwMjExMjM1OTU5WjCBkDELMAkGA1UEBhMCR0IxGzAZBgNVBAgT
  EkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEaMBgGA1UEChMR
  Q09NT0RPIENBIExpbWl0ZWQxNjA0BgNVBAMTLUNPTU9ETyBSU0EgRG9tYWluIFZh
  bGlkYXRpb24gU2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEP
  ADCCAQoCggEBAI7CAhnhoFmk6zg1jSz9AdDTScBkxwtiBUUWOqigwAwCfx3M28Sh
  bXcDow+G+eMGnD4LgYqbSRutA776S9uMIO3Vzl5ljj4Nr0zCsLdFXlIvNN5IJGS0
  Qa4Al/e+Z96e0HqnU4A7fK31llVvl0cKfIWLIpeNs4TgllfQcBhglo/uLQeTnaG6
  ytHNe+nEKpooIZFNb5JPJaXyejXdJtxGpdCsWTWM/06RQ1A/WZMebFEh7lgUq/51
  UHg+TLAchhP6a5i84DuUHoVS3AOTJBhuyydRReZw3iVDpA3hSqXttn7IzW3uLh0n
  c13cRTCAquOyQQuvvUSH2rnlG51/ruWFgqUCAwEAAaOCAWUwggFhMB8GA1UdIwQY
  MBaAFLuvfgI9+qbxPISOre44mOzZMjLUMB0GA1UdDgQWBBSQr2o6lFoL2JDqElZz
  30O0Oija5zAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV
  HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwGwYDVR0gBBQwEjAGBgRVHSAAMAgG
  BmeBDAECATBMBgNVHR8ERTBDMEGgP6A9hjtodHRwOi8vY3JsLmNvbW9kb2NhLmNv
  bS9DT01PRE9SU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDBxBggrBgEFBQcB
  AQRlMGMwOwYIKwYBBQUHMAKGL2h0dHA6Ly9jcnQuY29tb2RvY2EuY29tL0NPTU9E
  T1JTQUFkZFRydXN0Q0EuY3J0MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21v
  ZG9jYS5jb20wDQYJKoZIhvcNAQEMBQADggIBAE4rdk+SHGI2ibp3wScF9BzWRJ2p
  mj6q1WZmAT7qSeaiNbz69t2Vjpk1mA42GHWx3d1Qcnyu3HeIzg/3kCDKo2cuH1Z/
  e+FE6kKVxF0NAVBGFfKBiVlsit2M8RKhjTpCipj4SzR7JzsItG8kO3KdY3RYPBps
  P0/HEZrIqPW1N+8QRcZs2eBelSaz662jue5/DJpmNXMyYE7l3YphLG5SEXdoltMY
  dVEVABt0iN3hxzgEQyjpFv3ZBdRdRydg1vs4O2xyopT4Qhrf7W8GjEXCBgCq5Ojc
  2bXhc3js9iPc0d1sjhqPpepUfJa3w/5Vjo1JXvxku88+vZbrac2/4EjxYoIQ5QxG
  V/Iz2tDIY+3GH5QFlkoakdH368+PUq4NCNk+qKBR6cGHdNXJ93SrLlP7u3r7l+L4
  HyaPs9Kg4DdbKDsx5Q5XLVq4rXmsXiBmGqW5prU5wfWYQ//u+aen/e7KJD2AFsQX
  j4rBYKEMrltDR5FL1ZoXX/nUh8HCjLfn4g8wGTeGrODcQgPmlKidrv0PJFGUzpII
  0fxQ8ANAe4hZ7Q7drNJ3gjTcBpUC2JD5Leo31Rpg0Gcg19hCC0Wvgmje3WYkN5Ap
  lBlGGSW4gNfL1IYoakRwJiNiqZ+Gb7+6kHDSVneFeO/qJakXzlByjAA6quPbYzSf
  +AZxAeKCINT+b72x
  -----END CERTIFICATE-----

  -----BEGIN CERTIFICATE-----
  MIIFdDCCBFygAwIBAgIQJ2buVutJ846r13Ci/ITeIjANBgkqhkiG9w0BAQwFADBv
  MQswCQYDVQQGEwJTRTEUMBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFk
  ZFRydXN0IEV4dGVybmFsIFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBF
  eHRlcm5hbCBDQSBSb290MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFow
  gYUxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
  BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMSswKQYD
  VQQDEyJDT01PRE8gUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIICIjANBgkq
  hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAkehUktIKVrGsDSTdxc9EZ3SZKzejfSNw
  AHG8U9/E+ioSj0t/EFa9n3Byt2F/yUsPF6c947AEYe7/EZfH9IY+Cvo+XPmT5jR6
  2RRr55yzhaCCenavcZDX7P0N+pxs+t+wgvQUfvm+xKYvT3+Zf7X8Z0NyvQwA1onr
  ayzT7Y+YHBSrfuXjbvzYqOSSJNpDa2K4Vf3qwbxstovzDo2a5JtsaZn4eEgwRdWt
  4Q08RWD8MpZRJ7xnw8outmvqRsfHIKCxH2XeSAi6pE6p8oNGN4Tr6MyBSENnTnIq
  m1y9TBsoilwie7SrmNnu4FGDwwlGTm0+mfqVF9p8M1dBPI1R7Qu2XK8sYxrfV8g/
  vOldxJuvRZnio1oktLqpVj3Pb6r/SVi+8Kj/9Lit6Tf7urj0Czr56ENCHonYhMsT
  8dm74YlguIwoVqwUHZwK53Hrzw7dPamWoUi9PPevtQ0iTMARgexWO/bTouJbt7IE
  IlKVgJNp6I5MZfGRAy1wdALqi2cVKWlSArvX31BqVUa/oKMoYX9w0MOiqiwhqkfO
  KJwGRXa/ghgntNWutMtQ5mv0TIZxMOmm3xaG4Nj/QN370EKIf6MzOi5cHkERgWPO
  GHFrK+ymircxXDpqR+DDeVnWIBqv8mqYqnK8V0rSS527EPywTEHl7R09XiidnMy/
  s1Hap0flhFMCAwEAAaOB9DCB8TAfBgNVHSMEGDAWgBStvZh6NLQm9/rEJlTvA73g
  JMtUGjAdBgNVHQ4EFgQUu69+Aj36pvE8hI6t7jiY7NkyMtQwDgYDVR0PAQH/BAQD
  AgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAGBgRVHSAAMEQGA1UdHwQ9
  MDswOaA3oDWGM2h0dHA6Ly9jcmwudXNlcnRydXN0LmNvbS9BZGRUcnVzdEV4dGVy
  bmFsQ0FSb290LmNybDA1BggrBgEFBQcBAQQpMCcwJQYIKwYBBQUHMAGGGWh0dHA6
  Ly9vY3NwLnVzZXJ0cnVzdC5jb20wDQYJKoZIhvcNAQEMBQADggEBAGS/g/FfmoXQ
  zbihKVcN6Fr30ek+8nYEbvFScLsePP9NDXRqzIGCJdPDoCpdTPW6i6FtxFQJdcfj
  Jw5dhHk3QBN39bSsHNA7qxcS1u80GH4r6XnTq1dFDK8o+tDb5VCViLvfhVdpfZLY
  Uspzgb8c8+a4bmYRBbMelC1/kZWSWfFMzqORcUx8Rww7Cxn2obFshj5cqsQugsv5
  B5a6SE2Q8pTIqXOi6wZ7I53eovNNVZ96YUWYGGjHXkBrI/V5eu+MtWuLt29G9Hvx
  PUsE2JOAWVrgQSQdso8VYFhH2+9uRv0V9dlfmrPb2LjkQLPNlzmuhbsdjrzch5vR
  pu/xO28QOG8=
  -----END CERTIFICATE-----

  -----BEGIN CERTIFICATE-----
  MIIENjCCAx6gAwIBAgIBATANBgkqhkiG9w0BAQUFADBvMQswCQYDVQQGEwJTRTEU
  MBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFkZFRydXN0IEV4dGVybmFs
  IFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBFeHRlcm5hbCBDQSBSb290
  MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFowbzELMAkGA1UEBhMCU0Ux
  FDASBgNVBAoTC0FkZFRydXN0IEFCMSYwJAYDVQQLEx1BZGRUcnVzdCBFeHRlcm5h
  bCBUVFAgTmV0d29yazEiMCAGA1UEAxMZQWRkVHJ1c3QgRXh0ZXJuYWwgQ0EgUm9v
  dDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALf3GjPm8gAELTngTlvt
  H7xsD821+iO2zt6bETOXpClMfZOfvUq8k+0DGuOPz+VtUFrWlymUWoCwSXrbLpX9
  uMq/NzgtHj6RQa1wVsfwTz/oMp50ysiQVOnGXw94nZpAPA6sYapeFI+eh6FqUNzX
  mk6vBbOmcZSccbNQYArHE504B4YCqOmoaSYYkKtMsE8jqzpPhNjfzp/haW+710LX
  a0Tkx63ubUFfclpxCDezeWWkWaCUN/cALw3CknLa0Dhy2xSoRcRdKn23tNbE7qzN
  E0S3ySvdQwAl+mG5aWpYIxG3pzOPVnVZ9c0p10a3CitlttNCbxWyuHv77+ldU9U0
  WicCAwEAAaOB3DCB2TAdBgNVHQ4EFgQUrb2YejS0Jvf6xCZU7wO94CTLVBowCwYD
  VR0PBAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wgZkGA1UdIwSBkTCBjoAUrb2YejS0
  Jvf6xCZU7wO94CTLVBqhc6RxMG8xCzAJBgNVBAYTAlNFMRQwEgYDVQQKEwtBZGRU
  cnVzdCBBQjEmMCQGA1UECxMdQWRkVHJ1c3QgRXh0ZXJuYWwgVFRQIE5ldHdvcmsx
  IjAgBgNVBAMTGUFkZFRydXN0IEV4dGVybmFsIENBIFJvb3SCAQEwDQYJKoZIhvcN
  AQEFBQADggEBALCb4IUlwtYj4g+WBpKdQZic2YR5gdkeWxQHIzZlj7DYd7usQWxH
  YINRsPkyPef89iYTx4AWpb9a/IfPeHmJIZriTAcKhjW88t5RxNKWt9x+Tu5w/Rw5
  6wwCURQtjr0W4MHfRnXnJK3s9EK0hZNwEGe6nQY1ShjTK3rMUUKhemPR5ruhxSvC
  Nr4TDea9Y355e6cJDUCrat2PisP29owaQgVR1EX1n6diIWgVIEM8med8vSTYqZEX
  c4g/VhsxOBi0cQ+azcgOno4uG+GMmIPLHzHxREzGBHNJdmAPx/i9F4BrLunMTA5a
  mnkPIAou1Z5jJh5VkpTYghdae9C8x49OhgQ=
  -----END CERTIFICATE-----


# If you're committing your keys to your git repo, you'd probably want it encrypted.
# You can use ansible-vault to do this.
ssl_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEA4K6O9PqrVqrpm96BUVk+6PXU4bKBG0YVOA/SyJzRR2apJGlp
  f+V8WNWUhDEd2g6K4Z2k5VTnVFjbzGH8IKNQD+tQ2ozDPfTGxdfj9ZML0L2G6+fR
  jx+L5qdAHF7i+kbc4ghnDyzM3laMQcn18dNzH3OWhBT1YmCxkvwiKBECXPHMHJrb
  GOg/+pG2ULM6RhJsvkVlyYSnG8O6cDfXv4XH18tpabxQOGRmzRh0IreTXUKoxnXO
  OBiaXj/gcGUyLU64tRj3CWxk6+N3GJbn6V8ncv2dLh1nJ5mFNqFXFxPLoHSuxxTM
  Xm4g74yjyfTOEiC+Eq+mGlTIlIk1QI6Stcpi1wIDAQABAoIBAQDM9lCRKK7u5AEx
  4Lvlgt2B1Oh7b8SZJcirmLu3qF69nOhFwCeutaFGxKe0I75Qsp19DbtkPZy99EWm
  X+iJuZGKxCbBCFH/jfFagASDfL31kT+oqpQf1S5hnkc82k6C8+wCAppJXJwTY66V
  QXCsRzGpCl/PY/Mp6H11Ua6zEDkwoOlpQ9V4kWxVfQqkpFNv+SGz1RqgmWalrjBS
  Rt9gIylzClnJHGHUeRf9uOWpXlR5EJ2xQJnfPygbrmEq7voVF57kcoxFDMHibY8k
  oAPC0Bz7a/N47aR9b3GxGxndt+E2ZH6FQlWXjMVdSZEWLIl7vn72q2PC+6GXsuxz
  zKEZIG/pAoGBAPxTLYnngjfgBbrq02T/CRnJ3XJ1AZlC1uFFxogxx1iUhyjR3nl7
  duqEEhNjS3N8sBVK9qH12IwrvXDO87CwHzQRFPJwR019zZJtyDtaAOB2pkS3PFYt
  kQVD2DUNz46B7BaR2xv30Fmn+BSKzUGtOSaukT9YV31JRjuuXCN6OK0FAoGBAOP0
  T3A8Xpk3lfZ7yjEFxrFssV4uLvv8m55ZsrPsiWdYLklOHeTHgkQoTnoNpFKCpFoN
  elIiQlp3AtMAfZS9meaEwmkDWfqaTLafOUtig8aWW1mFxYFou2W6LsMm4uVmr8v3
  M3fLDKCQ0fL66M9TNzvWMtVThTuOYltqjK2l+HcrAoGBAL5iYETiWl2geZJcZp6Y
  1BwSNTWMVWV3ijy1ciQHMzuB7i19lNiisMooVp8sV5zO4uleA5OWtQqmYi0A6dxS
  N2kIzn5S+2nb10V58g/eTDURMUk93JfFj9uiIjt9rTMAkstAyEtlA17ynvuY82Bv
  vGSUaOGb3X+ZzxVu7PST3rmlAoGBAJZOSHb8B3BFu6cb9rUeVuY0gjtUfnx/Eul1
  waRrqiovdc22KXXpq1ZfsWc/SYNySwZp7qbrmg7mfEE/CI8j+a+LCFmP8SuRxFWC
  ZZf0bGlsSO2djB6JPU+VVTIumNukOvRlmlU52Kii9RyfHxVdjITy9u+8s5QSjX4z
  onD5h/yjAoGAH6LPKU2tpXU0DxStIQAXU+GlM2u6ZctiZxkxOxaCd2pAP2BZqM5h
  amls2344n7/N522/QgFud6k2hYmmOzYYQaiuMkvDNXpU3gCzcn3pcE7uyl3kx+qX
  am114oxorIaGU9o10TE7SXBRc0xhznVmVTVIlVez0GblDsKTqYXVq44=
  -----END RSA PRIVATE KEY-----