---

- name: Add llvmlite to apt-get list
  apt_repository: repo="deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main"

- name: Install llvmlite required packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - zlib1g
    - zlib1g-dev
    - libedit2
    - libedit-dev
    - llvm-3.7
    - llvm-3.7-dev
    - llvm-dev

- name: Install pip requirements for llvmlite
  pip: virtualenv={{ virtualenv_path }} name={{ item }}
  with_items:
    - enum34
    - funcsigs


- name: Clone llvmlite
  git: repo=https://github.com/numba/llvmlite.git
       dest="/tmp/llvmlite"
       version=v0.10.0
  sudo: yes
  sudo_user: root

- name: Install llvmlite
  shell: LLVM_CONFIG=/usr/bin/llvm-config-3.7 python setup.py install
  args:
    chdir: "/tmp/llvmlite"
  sudo: yes
  sudo_user: root